//! HTML fragment -> searchable plain text.
//!
//! Three of the four Google Takeout formats store prose as HTML rather than text:
//! `safeHtmlItem[].html` in both activity logs, and every `USER:`/`MODEL:` block in a
//! NotebookLM chat session. The index wants text, so something has to strip it.
//!
//! # Why this is hand-rolled
//!
//! `cs-import` depends on `serde_json` and `thiserror` and nothing else. Adding `scraper` or
//! `html5ever` buys correctness against *arbitrary* HTML, and this is not arbitrary HTML —
//! it is generated by one producer from Markdown, and the vocabulary is closed. Measured
//! over all 4.5 MB of fragments in the reference export:
//!
//! ```text
//! tags      strong li p ul em h3 code td tr th hr h2 ol a h4 br blockquote pre
//!           table thead tbody img sub span h1 div s h5      — 28, no others
//! entities  &quot; &#39; &amp; &gt; &lt; &#34;                — 6 forms, no others
//! ```
//!
//! No script, no style, no comments, no nesting that matters, no unclosed tags. A parser
//! that handles the whole language would be carrying weight this input never exercises.
//! `&nbsp;` and the numeric/hex escapes are decoded anyway: they cost two match arms and
//! Google's HTML *wrapper* used them even though the fragments do not.
//!
//! # What it deliberately does not do
//!
//! Nothing here tries to reproduce layout. Bold, italic and link *targets* are dropped
//! rather than turned into Markdown, because the output is indexed and previewed as prose:
//! `**` around a word makes it a different token to fts5 for no reading benefit. Link text
//! is kept, since that is the part a person searches for.

/// Strip an HTML fragment to plain text.
///
/// Block-level tags become line breaks, `<li>` becomes a bullet, table cells are separated
/// by ` | `, and entities are decoded. Runs of blank lines collapse to one, so the output
/// looks like the prose the fragment was rendered from.
pub(crate) fn to_text(html: &str) -> String {
    let mut out = String::with_capacity(html.len());
    let bytes = html.as_bytes();
    let mut i = 0;

    while i < bytes.len() {
        match bytes[i] {
            b'<' => match tag_at(html, i) {
                Some((name, closing, end)) => {
                    push_break_for(&mut out, &name, closing);
                    i = end;
                }
                // A bare `<` that opens nothing is text — a comparison in a code block,
                // most often. Keeping it is why `a < b` survives this pass intact.
                None => {
                    out.push('<');
                    i += 1;
                }
            },
            b'&' => match entity_at(html, i) {
                Some((decoded, end)) => {
                    out.push_str(decoded);
                    i = end;
                }
                None => {
                    out.push('&');
                    i += 1;
                }
            },
            _ => {
                // Multi-byte UTF-8 has to move by the whole character, not by one byte.
                let ch = html[i..].chars().next().expect("index is on a char boundary");
                out.push(ch);
                i += ch.len_utf8();
            }
        }
    }

    tidy(&out)
}

/// Read the tag starting at `open`, returning its lowercased name, whether it is a closing
/// tag, and the byte index just past `>`.
///
/// Returns `None` when this `<` does not begin a tag, which is what keeps a stray `<` in
/// prose from swallowing the rest of the text as if it were markup.
fn tag_at(html: &str, open: usize) -> Option<(String, bool, usize)> {
    let bytes = html.as_bytes();
    let mut i = open + 1;
    let closing = bytes.get(i) == Some(&b'/');
    if closing {
        i += 1;
    }

    let name_start = i;
    while i < bytes.len() && bytes[i].is_ascii_alphanumeric() {
        i += 1;
    }
    if i == name_start {
        return None;
    }
    let name = html[name_start..i].to_ascii_lowercase();

    // Attributes, if any, run to the first `>`. Values here never contain one — these
    // fragments carry hrefs and `src`s, not inline event handlers with expressions.
    let close = html[i..].find('>')? + i;
    Some((name, closing, close + 1))
}

/// Emit whatever separator a tag implies. Inline tags imply nothing and fall through.
fn push_break_for(out: &mut String, name: &str, closing: bool) {
    match name {
        // A list item opens a line and marks it, so the bullets survive into the preview.
        "li" if !closing => {
            newline(out);
            out.push_str("- ");
        }
        // Cells are separated rather than broken: a table row reads as one line.
        "td" | "th" if closing => out.push_str(" | "),
        "br" => newline(out),
        "hr" => {
            newline(out);
            out.push_str("---");
            newline(out);
        }
        "p" | "div" | "ul" | "ol" | "li" | "tr" | "table" | "thead" | "tbody" | "blockquote"
        | "pre" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" => newline(out),
        // strong, em, code, a, span, sub, s, img, and anything unrecognised: no break. An
        // unknown tag is far more likely to be inline emphasis than a new block, and
        // guessing "block" would shatter a paragraph mid-sentence.
        _ => {}
    }
}

fn newline(out: &mut String) {
    if !out.ends_with('\n') {
        out.push('\n');
    }
}

/// Decode the entity starting at `amp`, returning the text and the index just past `;`.
fn entity_at(html: &str, amp: usize) -> Option<(&'static str, usize)> {
    // Longest real entity here is `&hellip;` at 8; the bound stops a lone `&` in prose from
    // scanning to the end of a 100 KB response looking for a semicolon that is not coming.
    //
    // Bounded by *characters* rather than bytes. `&amp;` is ASCII, so the two agree on any
    // real entity — but the bound also has to be safe on a lone `&` followed by prose, and
    // `html[amp..amp + 12]` panics outright when the 12th byte lands inside a multi-byte
    // character. A curly apostrophe eleven bytes after an ampersand is enough to do it, and
    // the reference export has one.
    let semi = html[amp..]
        .char_indices()
        .take(12)
        .find(|&(_, c)| c == ';')
        .map(|(offset, _)| amp + offset)?;
    let body = &html[amp + 1..semi];
    let end = semi + 1;

    let decoded = match body {
        "amp" => "&",
        "lt" => "<",
        "gt" => ">",
        "quot" => "\"",
        "apos" => "'",
        "nbsp" | "ensp" | "emsp" | "thinsp" => " ",
        "mdash" => "—",
        "ndash" => "–",
        "hellip" => "…",
        numeric if numeric.starts_with('#') => return numeric_entity(&numeric[1..], end),
        _ => return None,
    };
    Some((decoded, end))
}

/// `&#39;` and `&#x27;`. Only the handful of code points these fragments actually use are
/// mapped; anything else is left as literal text rather than silently becoming a wrong glyph.
fn numeric_entity(digits: &str, end: usize) -> Option<(&'static str, usize)> {
    let code = match digits.strip_prefix(['x', 'X']) {
        Some(hex) => u32::from_str_radix(hex, 16).ok()?,
        None => digits.parse::<u32>().ok()?,
    };
    let decoded = match code {
        34 => "\"",
        38 => "&",
        39 => "'",
        60 => "<",
        62 => ">",
        160 => " ",
        _ => return None,
    };
    Some((decoded, end))
}

/// Trim trailing spaces from each line and drop blank lines entirely.
///
/// Dropping rather than collapsing-to-one, because these fragments carry their own newlines
/// *between* tags on top of the ones the tags imply, and only sometimes: NotebookLM writes
/// `</p>\n<p>` while `safeHtmlItem` writes `</p><p>`. Preserving blank lines would make the
/// spacing of the output depend on that incidental whitespace, so the same two paragraphs
/// would render one way from one format and another way from the next. One newline per block
/// is the rule that does not vary, and it keeps a 100 KB response from doubling in height in
/// a preview pane that has to show it.
fn tidy(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for line in s.lines() {
        // ` | ` on the end of a row is the separator after the final cell.
        let line = line.trim_end().trim_end_matches(" |").trim_end();
        // A bullet with nothing after it is an artifact of an empty `<li>`, not content.
        if line.is_empty() || line == "-" {
            continue;
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(line);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn block_tags_become_line_breaks_and_inline_tags_disappear() {
        assert_eq!(
            to_text("<p>The <strong>witness</strong> must be an <em>assignment</em>.</p><p>Second.</p>"),
            "The witness must be an assignment.\nSecond."
        );
    }

    #[test]
    fn list_items_keep_a_bullet_so_the_preview_still_reads_as_a_list() {
        assert_eq!(
            to_text("<ul><li>SAT</li><li>3SAT</li></ul>"),
            "- SAT\n- 3SAT"
        );
    }

    #[test]
    fn a_table_row_reads_as_one_line_with_separated_cells() {
        assert_eq!(
            to_text("<table><tr><th>Problem</th><th>Witness</th></tr><tr><td>SAT</td><td>assignment</td></tr></table>"),
            "Problem | Witness\nSAT | assignment"
        );
    }

    #[test]
    fn the_six_entity_forms_google_actually_emits_all_decode() {
        assert_eq!(
            to_text("&quot;a&#39;b&amp;c&gt;d&lt;e&#34;"),
            "\"a'b&c>d<e\""
        );
    }

    #[test]
    fn a_bare_less_than_in_prose_is_text_and_does_not_eat_the_rest() {
        // A code block comparing two values is the common case, and treating this `<` as
        // markup would delete everything after it.
        assert_eq!(to_text("<p>when a < b holds</p>"), "when a < b holds");
        assert_eq!(to_text("<p>5 &lt; 6 and a < b</p>"), "5 < 6 and a < b");
    }

    #[test]
    fn a_lone_ampersand_is_kept_rather_than_scanning_for_a_distant_semicolon() {
        assert_eq!(to_text("<p>Tom & Jerry; later</p>"), "Tom & Jerry; later");
    }

    #[test]
    fn tags_carrying_attributes_are_stripped_whole() {
        assert_eq!(
            to_text(r#"<p>See <a href="https://example.com/x?a=1&amp;b=2">the docs</a>.</p>"#),
            "See the docs."
        );
        assert_eq!(to_text(r#"<p>a<img src="x.png" alt="y">b</p>"#), "ab");
    }

    #[test]
    fn spacing_does_not_depend_on_whitespace_between_the_source_tags() {
        // The same three paragraphs, written the way `safeHtmlItem` writes them and the way
        // NotebookLM writes them. They have to come out identical.
        assert_eq!(to_text("<p>one</p><p>two</p><p>three</p>"), "one\ntwo\nthree");
        assert_eq!(to_text("<p>one</p>\n<p>two</p>\n<p>three</p>"), "one\ntwo\nthree");
        assert_eq!(to_text("<p>one</p>\n\n<p>two</p>\n\n\n<p>three</p>"), "one\ntwo\nthree");
    }

    #[test]
    fn a_horizontal_rule_survives_as_a_readable_divider() {
        assert_eq!(to_text("<p>above</p><hr><p>below</p>"), "above\n---\nbelow");
    }

    #[test]
    fn an_unknown_tag_is_treated_as_inline_rather_than_splitting_a_sentence() {
        assert_eq!(to_text("<p>a <mark>b</mark> c</p>"), "a b c");
    }

    #[test]
    fn multibyte_text_is_not_cut_mid_character() {
        assert_eq!(to_text("<p>café — naïve 日本語</p>"), "café — naïve 日本語");
    }

    #[test]
    fn a_multibyte_character_just_past_the_entity_scan_window_does_not_panic() {
        // Regression, and it took the real export to find it: a bare `&` whose 12-byte
        // lookahead for a `;` ends inside a curly apostrophe. Byte-slicing there panics
        // rather than failing to match, so this crashed `cs index` outright.
        assert_eq!(to_text("& 123456789’"), "& 123456789’");
        assert_eq!(to_text("<p>Tom & Jerry’s ’’’ day</p>"), "Tom & Jerry’s ’’’ day");
        // The same window, but the entity is real and still has to decode.
        assert_eq!(to_text("&amp; 123456789’"), "& 123456789’");
    }

    #[test]
    fn empty_and_tag_only_input_produce_nothing() {
        assert_eq!(to_text(""), "");
        assert_eq!(to_text("<p></p><ul><li></li></ul>"), "");
    }
}
