[package]
name = "cs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "cs"
path = "src/main.rs"

[dependencies]
cs-archive = { path = "../cs-archive" }
cs-core = { path = "../cs-core" }
cs-tui = { path = "../cs-tui" }
cs-import = { path = "../cs-import" }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
