//! The contract between importers and the index.
//!
//! An importer's whole job is to turn archived bytes into these types. Nothing here knows
//! about SQLite, and nothing here knows where the bytes came from.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    User,
    Assistant,
    Tool,
    System,
}

impl Role {
    pub fn as_str(self) -> &'static str {
        match self {
            Role::User => "user",
            Role::Assistant => "assistant",
            Role::Tool => "tool",
            Role::System => "system",
        }
    }
}

/// What a message *is*, as distinct from who sent it. Only `Prose` is searched by default:
/// tool traffic is 91% of the corpus text and would otherwise dominate ranking (ADR 5).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Kind {
    Prose,
    Reasoning,
    ToolCall,
    ToolResult,
}

impl Kind {
    /// Every variant, so a rule expressed over kinds can be *derived* by a caller rather than
    /// restated. `cs explain` builds its list of unindexed kinds this way, which is what keeps
    /// its answer true if [`Kind::is_indexed`] ever changes its mind.
    pub const ALL: [Kind; 4] = [Kind::Prose, Kind::Reasoning, Kind::ToolCall, Kind::ToolResult];

    pub fn as_str(self) -> &'static str {
        match self {
            Kind::Prose => "prose",
            Kind::Reasoning => "reasoning",
            Kind::ToolCall => "tool_call",
            Kind::ToolResult => "tool_result",
        }
    }
    pub fn is_tool(self) -> bool {
        matches!(self, Kind::ToolCall | Kind::ToolResult)
    }

    /// Whether the indexer writes postings for this kind, and so whether search can find it.
    ///
    /// `Reasoning` is the one kind that answers `false`, and it is a decision rather than an
    /// oversight (chat-search-8mb). Measured through fts5 with the real tokenizer, indexing it
    /// would have surfaced no conversation that prose and tool traffic do not already surface:
    /// reasoning is *about* work that also appears in prose, so it is redundant for finding.
    /// What it is not redundant for is reading — 47% of its vocabulary never appears elsewhere
    /// in its own conversation — which is why the preview draws it and this does not index it.
    /// The head of that unique vocabulary is also why it would cost something to index:
    /// `preparing`, `summarizing`, `verifying` in their hundreds, which is exactly the noise
    /// ADR 5 keeps out of prose BM25.
    ///
    /// Matched exhaustively rather than with `matches!`, so a new [`Kind`] cannot default into
    /// either answer — whoever adds one has to say which it is.
    ///
    /// This is about the *kind*. A message of an indexed kind whose stored text is empty still
    /// gets no posting; see `crate::index::write_one`.
    pub fn is_indexed(self) -> bool {
        match self {
            Kind::Prose | Kind::ToolCall | Kind::ToolResult => true,
            Kind::Reasoning => false,
        }
    }
}

/// Title candidates, kept separate so the fold happens in one place rather than each
/// importer inventing its own precedence (ADR 8).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Titles {
    /// A user rename. Outranks everything derived.
    pub custom: Option<String>,
    /// Generated by the tool, e.g. Claude Code's `ai-title`.
    pub generated: Option<String>,
    /// Fallback: the opening user message, truncated.
    pub first_user: Option<String>,
}

impl Titles {
    pub fn resolve(&self) -> Option<&str> {
        self.custom
            .as_deref()
            .or(self.generated.as_deref())
            .or(self.first_user.as_deref())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Unique within its conversation. Scope by transcript file where the source's own id
    /// is only file-unique — subagent threads share a session id (ADR 2).
    pub native_id: String,
    /// Parent within the conversation DAG, in the same id space as `native_id`.
    ///
    /// Must name a message the importer actually **emitted**. Every source has nodes that
    /// get skipped — structural roots, `isMeta` turns, empty or image-only messages — and
    /// when one of those sits mid-chain the importer has to re-parent its children to the
    /// nearest surviving ancestor rather than pointing at the node it dropped.
    ///
    /// This is not cosmetic. `index::on_head_path` walks these edges through a map built
    /// from emitted messages only, so a dangling parent silently terminates the walk and
    /// marks every message above it as off-head-path — a search result that quietly claims
    /// to be on an abandoned branch when it is not.
    pub parent_native_id: Option<String>,
    /// Which thread this belongs to — usually the transcript file it came from. Carried
    /// explicitly rather than parsed back out of `native_id` (ADR 4).
    pub thread_key: String,
    pub is_sidechain: bool,
    pub seq: i64,
    pub role: Role,
    pub kind: Kind,
    /// Epoch milliseconds.
    pub ts: Option<i64>,
    /// This message reports a failure — a tool that did not do what it was asked.
    ///
    /// Only ever true on [`Kind::ToolResult`]. It exists because a *failed* result is
    /// recognition information in a way a successful one is not: a preview omits the
    /// successful ones, since the call already implies the result, but "the tool broke here"
    /// is often exactly what makes a conversation the one you were looking for.
    ///
    /// Derived from each source's own signal, never from the text. Claude Code sets
    /// `is_error` on the `tool_result` block; Codex carries `metadata.exit_code` in its
    /// `function_call_output` (measured over 60 rollouts: 2,054 outputs carry one, 132 of
    /// them non-zero). Sources with no signal leave it false rather than guessing — sniffing
    /// for the word "error" would hide working results and surface broken ones.
    pub is_error: bool,
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    pub source: String,
    pub native_id: String,
    pub titles: Titles,
    pub cwd: Option<String>,
    pub git_branch: Option<String>,
    pub model: Option<String>,
    /// Fine-grained origin — `codex_vscode`, `claude-vscode`. Derived, never part of an id.
    pub surface: Option<String>,
    /// Cross-conversation lineage: this conversation was forked from another (ADR 4).
    pub forked_from_native_id: Option<String>,
    /// Currently-selected leaf. `None` means "last message of the main thread", which is
    /// right for every append-only CLI source; ChatGPT supplies its own `current_node`.
    pub head_native_id: Option<String>,
    pub messages: Vec<Message>,
}

impl Conversation {
    pub fn id(&self) -> String {
        format!("{}:{}", self.source, self.native_id)
    }

    pub fn message_id(&self, native_id: &str) -> String {
        format!("{}:{}:{}", self.source, self.native_id, native_id)
    }

    /// The head, falling back to the last non-sidechain message.
    pub fn resolved_head(&self) -> Option<&str> {
        if let Some(h) = &self.head_native_id {
            return Some(h);
        }
        self.messages
            .iter()
            .filter(|m| !m.is_sidechain)
            .max_by_key(|m| m.seq)
            .map(|m| m.native_id.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_precedence_puts_a_user_rename_first() {
        let t = Titles {
            custom: Some("Image Readibility".into()),
            generated: Some("Analysis of image contrast".into()),
            first_user: Some("can you look at this".into()),
        };
        assert_eq!(t.resolve(), Some("Image Readibility"));

        let t = Titles { custom: None, ..t };
        assert_eq!(t.resolve(), Some("Analysis of image contrast"));

        let t = Titles { generated: None, ..t };
        assert_eq!(t.resolve(), Some("can you look at this"));

        assert_eq!(Titles::default().resolve(), None);
    }

    fn msg(native: &str, seq: i64, sidechain: bool) -> Message {
        Message {
            native_id: native.into(),
            parent_native_id: None,
            thread_key: "t".into(),
            is_sidechain: sidechain,
            is_error: false,
            seq,
            role: Role::User,
            kind: Kind::Prose,
            ts: Some(seq),
            text: "x".into(),
        }
    }

    #[test]
    fn head_defaults_to_the_last_main_thread_message() {
        let c = Conversation {
            source: "codex".into(),
            native_id: "abc".into(),
            titles: Titles::default(),
            cwd: None,
            git_branch: None,
            model: None,
            surface: None,
            forked_from_native_id: None,
            head_native_id: None,
            // a later subagent message must not become the head
            messages: vec![msg("a", 1, false), msg("b", 2, false), msg("s", 3, true)],
        };
        assert_eq!(c.resolved_head(), Some("b"));
        assert_eq!(c.id(), "codex:abc");
        assert_eq!(c.message_id("b"), "codex:abc:b");
    }
}
