//! The contract between importers and the index.
//!
//! An importer's whole job is to turn archived bytes into these types. Nothing here knows
//! about SQLite, and nothing here knows where the bytes came from.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    User,
    Assistant,
    Tool,
    System,
}

impl Role {
    pub fn as_str(self) -> &'static str {
        match self {
            Role::User => "user",
            Role::Assistant => "assistant",
            Role::Tool => "tool",
            Role::System => "system",
        }
    }
}

/// What a message *is*, as distinct from who sent it. Only `Prose` is searched by default:
/// tool traffic is 91% of the corpus text and would otherwise dominate ranking (ADR 5).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Kind {
    Prose,
    Reasoning,
    ToolCall,
    ToolResult,
}

impl Kind {
    pub fn as_str(self) -> &'static str {
        match self {
            Kind::Prose => "prose",
            Kind::Reasoning => "reasoning",
            Kind::ToolCall => "tool_call",
            Kind::ToolResult => "tool_result",
        }
    }
    pub fn is_tool(self) -> bool {
        matches!(self, Kind::ToolCall | Kind::ToolResult)
    }
}

/// Title candidates, kept separate so the fold happens in one place rather than each
/// importer inventing its own precedence (ADR 8).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Titles {
    /// A user rename. Outranks everything derived.
    pub custom: Option<String>,
    /// Generated by the tool, e.g. Claude Code's `ai-title`.
    pub generated: Option<String>,
    /// Fallback: the opening user message, truncated.
    pub first_user: Option<String>,
}

impl Titles {
    pub fn resolve(&self) -> Option<&str> {
        self.custom
            .as_deref()
            .or(self.generated.as_deref())
            .or(self.first_user.as_deref())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Unique within its conversation. Scope by transcript file where the source's own id
    /// is only file-unique — subagent threads share a session id (ADR 2).
    pub native_id: String,
    /// Parent within the conversation DAG, in the same id space as `native_id`.
    pub parent_native_id: Option<String>,
    /// Which thread this belongs to — usually the transcript file it came from. Carried
    /// explicitly rather than parsed back out of `native_id` (ADR 4).
    pub thread_key: String,
    pub is_sidechain: bool,
    pub seq: i64,
    pub role: Role,
    pub kind: Kind,
    /// Epoch milliseconds.
    pub ts: Option<i64>,
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    pub source: String,
    pub native_id: String,
    pub titles: Titles,
    pub cwd: Option<String>,
    pub git_branch: Option<String>,
    pub model: Option<String>,
    /// Fine-grained origin — `codex_vscode`, `claude-vscode`. Derived, never part of an id.
    pub surface: Option<String>,
    /// Cross-conversation lineage: this conversation was forked from another (ADR 4).
    pub forked_from_native_id: Option<String>,
    /// How to reopen this in its native tool.
    pub resume_cmd: Option<String>,
    /// Currently-selected leaf. `None` means "last message of the main thread", which is
    /// right for every append-only CLI source; ChatGPT supplies its own `current_node`.
    pub head_native_id: Option<String>,
    pub messages: Vec<Message>,
}

impl Conversation {
    pub fn id(&self) -> String {
        format!("{}:{}", self.source, self.native_id)
    }

    pub fn message_id(&self, native_id: &str) -> String {
        format!("{}:{}:{}", self.source, self.native_id, native_id)
    }

    /// The head, falling back to the last non-sidechain message.
    pub fn resolved_head(&self) -> Option<&str> {
        if let Some(h) = &self.head_native_id {
            return Some(h);
        }
        self.messages
            .iter()
            .filter(|m| !m.is_sidechain)
            .max_by_key(|m| m.seq)
            .map(|m| m.native_id.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_precedence_puts_a_user_rename_first() {
        let t = Titles {
            custom: Some("Image Readibility".into()),
            generated: Some("Analysis of image contrast".into()),
            first_user: Some("can you look at this".into()),
        };
        assert_eq!(t.resolve(), Some("Image Readibility"));

        let t = Titles { custom: None, ..t };
        assert_eq!(t.resolve(), Some("Analysis of image contrast"));

        let t = Titles { generated: None, ..t };
        assert_eq!(t.resolve(), Some("can you look at this"));

        assert_eq!(Titles::default().resolve(), None);
    }

    fn msg(native: &str, seq: i64, sidechain: bool) -> Message {
        Message {
            native_id: native.into(),
            parent_native_id: None,
            thread_key: "t".into(),
            is_sidechain: sidechain,
            seq,
            role: Role::User,
            kind: Kind::Prose,
            ts: Some(seq),
            text: "x".into(),
        }
    }

    #[test]
    fn head_defaults_to_the_last_main_thread_message() {
        let c = Conversation {
            source: "codex".into(),
            native_id: "abc".into(),
            titles: Titles::default(),
            cwd: None,
            git_branch: None,
            model: None,
            surface: None,
            forked_from_native_id: None,
            resume_cmd: None,
            head_native_id: None,
            // a later subagent message must not become the head
            messages: vec![msg("a", 1, false), msg("b", 2, false), msg("s", 3, true)],
        };
        assert_eq!(c.resolved_head(), Some("b"));
        assert_eq!(c.id(), "codex:abc");
        assert_eq!(c.message_id("b"), "codex:abc:b");
    }
}
