[package]
name = "cs-archive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
blake3 = { workspace = true }
globset = { workspace = true }
reflink-copy = { workspace = true }
uuid = { workspace = true }
