// Generated by `python3 poc/ui/tokens.py terminal`. Do not edit by hand.
//
// The values are `poc/ui/styles.css` and `poc/ui/directions.css` read through the same
// cascade `poc/ui/palette.py --verify` reads them through, so the app and the prototype
// cannot drift: there is one authored copy of this palette and it is the one the mockup
// renders. This file is a build product that happens to be checked in, because the app
// has to build from a checkout with no Python in it.
//
// It is provenance and not a dependency. Nothing in `apps/` reads `poc/` at build or at
// run time, and regenerating is a thing a person does on purpose.
//
// `swift run -c release chat-search --verify-theme` re-measures what is below against
// the measurements that fence it, for the reason `palette.py --verify` exists: solving a
// colour and writing it down are two events, and only one of them was ever checked.

import SwiftUI

extension Theme {
    public static let terminal = Theme(
        name: "terminal",
        dark: Palette([
            .bg: RGB(0x1b2123),  // --bg
            .panel: RGB(0x161c1e),  // --panel
            .panel2: RGB(0x212a2c),  // --panel-2
            .panel3: RGB(0x283335),  // --panel-3
            .ink: RGB(0xe3e9e9),  // --ink
            .ink2: RGB(0x97a5a6),  // --ink-2
            .ink3: RGB(0x7a8b8e),  // --ink-3
            .rule: RGB(0x2a3335),  // --rule
            .rule2: RGB(0x3a4547),  // --rule-2
            .sel: RGB(0x4ec3c0),  // --sel
            .selBg: RGB(0x143a3b),  // --sel-bg
            .selInk: RGB(0x06201f),  // --sel-ink
            .hit: RGB(0xf0b95f),  // --hit
            .hitBg: RGB(0x4a3512),  // --hit-bg
            .err: RGB(0xe2796c),  // --err
            .ok: RGB(0x6fc98a),  // --ok
            .kUser: RGB(0x2bb6b2),  // --k-user
            .kAgent: RGB(0xd6dddc),  // --k-agent
            .kReason: RGB(0x9361bf),  // --k-reason
            .kTool: RGB(0x425258),  // --k-tool
            .actLook: RGB(0x354146),  // --act-look
            .actRun: RGB(0x425258),  // --act-run
            .actChange: RGB(0x486d65),  // --act-change
            .kToolInk: RGB(0x8fa0a3),  // --k-tool-ink
            .mapBg: RGB(0x10191a),  // --map-bg
            .srcClaudeCode: RGB(0xd9b551),  // --src-claude-code
            .srcCodex: RGB(0x5fd3d0),  // --src-codex
            .srcChatgpt: RGB(0x74c884),  // --src-chatgpt
            .srcClaudeAi: RGB(0xcf93d4),  // --src-claude-ai
            .srcGemini: RGB(0x86abf3),  // --src-gemini
        ]),
        light: Palette([
            .bg: RGB(0xfdfdfc),  // --bg
            .panel: RGB(0xf1f4f4),  // --panel
            .panel2: RGB(0xe7ebeb),  // --panel-2
            .panel3: RGB(0xdbe1e1),  // --panel-3
            .ink: RGB(0x101a1c),  // --ink
            .ink2: RGB(0x55666a),  // --ink-2
            .ink3: RGB(0x617175),  // --ink-3
            .rule: RGB(0xdfe4e4),  // --rule
            .rule2: RGB(0xc4cdcd),  // --rule-2
            .sel: RGB(0x0b5d63),  // --sel
            .selBg: RGB(0xd6e8e8),  // --sel-bg
            .selInk: RGB(0xffffff),  // --sel-ink
            .hit: RGB(0xa96a06),  // --hit
            .hitBg: RGB(0xffe9b8),  // --hit-bg
            .err: RGB(0xa3322a),  // --err
            .ok: RGB(0x2f7a3e),  // --ok
            .kUser: RGB(0x145654),  // --k-user
            .kAgent: RGB(0x202726),  // --k-agent
            .kReason: RGB(0x905dbd),  // --k-reason
            .kTool: RGB(0x91a5ac),  // --k-tool
            .actLook: RGB(0xabbac0),  // --act-look
            .actRun: RGB(0x91a5ac),  // --act-run
            .actChange: RGB(0x608f86),  // --act-change
            .kToolInk: RGB(0x5d6d70),  // --k-tool-ink
            .mapBg: RGB(0xeaeeee),  // --map-bg
            .srcClaudeCode: RGB(0x8a6a00),  // --src-claude-code
            .srcCodex: RGB(0x14707a),  // --src-codex
            .srcChatgpt: RGB(0x2f7a3e),  // --src-chatgpt
            .srcClaudeAi: RGB(0x8c4a93),  // --src-claude-ai
            .srcGemini: RGB(0x2b5bb5),  // --src-gemini
        ]),
        type: TypeScale(
            sizes: [
                .head: 13,  // --fs-head
                .body: 12.5,  // --fs-body
                .sub: 11.5,  // --fs-sub
                .meta: 10,  // --fs-meta
                .micro: 9,  // --fs-micro
            ],
            faces: [
                .ui: .default,  // --ui
                .mono: .monospaced,  // --mono
                .serif: .serif,  // --serif
            ]),
        geometry: Geometry([
            .r1: 3,  // --r-1
            .r2: 4,  // --r-2
            .r3: 5,  // --r-3
            .r4: 6,  // --r-4
            .r5: 7,  // --r-5
            .r6: 9,  // --r-6
            .rowPaddingX: 12,  // --row-px
            .rowPaddingTop: 7,  // --row-pt
            .rowPaddingBottom: 8,  // --row-pb
            .rowLead: 3,  // --row-lead
            .rowGap: 9,  // --row-gap
            .ribbonHeight: 18,  // --rib-h
            .ribbonTrack: 9,  // --rib-track
            .ribbonTop: 6,  // --rib-top
        ]))

    /// The direction this build draws.
    ///
    /// Regenerating this file for another direction moves every colour, size and radius in
    /// the app and touches nothing else — no view names a direction, and no view names a
    /// value. That is the claim; `git diff --stat` after a regeneration is the evidence.
    public static let shipped = terminal
}
