// Generated by `python3 poc/ui/tokens.py terminal paper blueprint ink gruvbox-derived solarized-derived`. Do not edit by hand.
//
// The values are `poc/ui/styles.css` and `poc/ui/directions.css` read through the same
// cascade `poc/ui/palette.py --verify` reads them through, so the app and the prototype
// cannot drift: there is one authored copy of these palettes and it is the one the mockup
// renders. This file is a build product that happens to be checked in, because the app
// has to build from a checkout with no Python in it.
//
// It is provenance and not a dependency. Nothing in `apps/` reads `poc/` at build or at
// run time, and regenerating is a thing a person does on purpose.
//
// `swift run -c release chat-search --verify-theme` re-measures every direction below
// against the measurements that fence it, for the reason `palette.py --verify` exists:
// solving a colour and writing it down are two events, and only one of them was ever
// checked. Every direction here is one the app offers, so every one of them is measured.

import SwiftUI

extension Theme {
    public static let terminal = Theme(
        name: "terminal",
        dark: Palette([
            .bg: RGB(0x1b2123),  // --bg
            .panel: RGB(0x161c1e),  // --panel
            .panel2: RGB(0x212a2c),  // --panel-2
            .panel3: RGB(0x283335),  // --panel-3
            .ink: RGB(0xe3e9e9),  // --ink
            .ink2: RGB(0x97a5a6),  // --ink-2
            .ink3: RGB(0x7a8b8e),  // --ink-3
            .rule: RGB(0x2a3335),  // --rule
            .rule2: RGB(0x3a4547),  // --rule-2
            .sel: RGB(0x4ec3c0),  // --sel
            .selBg: RGB(0x143a3b),  // --sel-bg
            .selInk: RGB(0x06201f),  // --sel-ink
            .hit: RGB(0xf0b95f),  // --hit
            .hitBg: RGB(0x4a3512),  // --hit-bg
            .err: RGB(0xe2796c),  // --err
            .ok: RGB(0x6fc98a),  // --ok
            .kUser: RGB(0x2bb6b2),  // --k-user
            .kAgent: RGB(0xd6dddc),  // --k-agent
            .kReason: RGB(0x9361bf),  // --k-reason
            .kTool: RGB(0x425258),  // --k-tool
            .actLook: RGB(0x354146),  // --act-look
            .actRun: RGB(0x425258),  // --act-run
            .actChange: RGB(0x486d65),  // --act-change
            .kToolInk: RGB(0x8fa0a3),  // --k-tool-ink
            .mapBg: RGB(0x10191a),  // --map-bg
            .srcClaudeCode: RGB(0xd9b551),  // --src-claude-code
            .srcCodex: RGB(0x5fd3d0),  // --src-codex
            .srcChatgpt: RGB(0x74c884),  // --src-chatgpt
            .srcClaudeAi: RGB(0xcf93d4),  // --src-claude-ai
            .srcGemini: RGB(0x86abf3),  // --src-gemini
        ]),
        light: Palette([
            .bg: RGB(0xfdfdfc),  // --bg
            .panel: RGB(0xf1f4f4),  // --panel
            .panel2: RGB(0xe7ebeb),  // --panel-2
            .panel3: RGB(0xdbe1e1),  // --panel-3
            .ink: RGB(0x101a1c),  // --ink
            .ink2: RGB(0x55666a),  // --ink-2
            .ink3: RGB(0x617175),  // --ink-3
            .rule: RGB(0xdfe4e4),  // --rule
            .rule2: RGB(0xc4cdcd),  // --rule-2
            .sel: RGB(0x0b5d63),  // --sel
            .selBg: RGB(0xd6e8e8),  // --sel-bg
            .selInk: RGB(0xffffff),  // --sel-ink
            .hit: RGB(0xa96a06),  // --hit
            .hitBg: RGB(0xffe9b8),  // --hit-bg
            .err: RGB(0xa3322a),  // --err
            .ok: RGB(0x2f7a3e),  // --ok
            .kUser: RGB(0x145654),  // --k-user
            .kAgent: RGB(0x202726),  // --k-agent
            .kReason: RGB(0x905dbd),  // --k-reason
            .kTool: RGB(0x91a5ac),  // --k-tool
            .actLook: RGB(0xabbac0),  // --act-look
            .actRun: RGB(0x91a5ac),  // --act-run
            .actChange: RGB(0x608f86),  // --act-change
            .kToolInk: RGB(0x5d6d70),  // --k-tool-ink
            .mapBg: RGB(0xeaeeee),  // --map-bg
            .srcClaudeCode: RGB(0x8a6a00),  // --src-claude-code
            .srcCodex: RGB(0x14707a),  // --src-codex
            .srcChatgpt: RGB(0x2f7a3e),  // --src-chatgpt
            .srcClaudeAi: RGB(0x8c4a93),  // --src-claude-ai
            .srcGemini: RGB(0x2b5bb5),  // --src-gemini
        ]),
        type: TypeScale(
            sizes: [
                .head: 13,  // --fs-head
                .body: 12.5,  // --fs-body
                .sub: 11.5,  // --fs-sub
                .meta: 10,  // --fs-meta
                .micro: 9,  // --fs-micro
            ],
            faces: [
                .ui: .default,  // --ui
                .mono: .monospaced,  // --mono
                .serif: .serif,  // --serif
            ]),
        geometry: Geometry([
            .r1: 3,  // --r-1
            .r2: 4,  // --r-2
            .r3: 5,  // --r-3
            .r4: 6,  // --r-4
            .r5: 7,  // --r-5
            .r6: 9,  // --r-6
            .rowPaddingX: 12,  // --row-px
            .rowPaddingTop: 7,  // --row-pt
            .rowPaddingBottom: 8,  // --row-pb
            .rowLead: 3,  // --row-lead
            .rowGap: 9,  // --row-gap
            .ribbonHeight: 18,  // --rib-h
            .ribbonTrack: 9,  // --rib-track
            .ribbonTop: 6,  // --rib-top
        ]))

    public static let paper = Theme(
        name: "paper",
        dark: Palette([
            .bg: RGB(0x1c1917),  // --bg
            .panel: RGB(0x15120f),  // --panel
            .panel2: RGB(0x262220),  // --panel-2
            .panel3: RGB(0x322c28),  // --panel-3
            .ink: RGB(0xece6da),  // --ink
            .ink2: RGB(0xb3a794),  // --ink-2
            .ink3: RGB(0x8e826f),  // --ink-3
            .rule: RGB(0x262019),  // --rule
            .rule2: RGB(0x3a322a),  // --rule-2
            .sel: RGB(0x8fa9cf),  // --sel
            .selBg: RGB(0x1e2836),  // --sel-bg
            .selInk: RGB(0x0b1420),  // --sel-ink
            .hit: RGB(0xe8b45f),  // --hit
            .hitBg: RGB(0x46320f),  // --hit-bg
            .err: RGB(0xdc7d6b),  // --err
            .ok: RGB(0x8fb26a),  // --ok
            .kUser: RGB(0x7aa2cb),  // --k-user
            .kAgent: RGB(0xd9d4ca),  // --k-agent
            .kReason: RGB(0x9959ad),  // --k-reason
            .kTool: RGB(0x504a42),  // --k-tool
            .actLook: RGB(0x3e3a35),  // --act-look
            .actRun: RGB(0x504a42),  // --act-run
            .actChange: RGB(0x526744),  // --act-change
            .kToolInk: RGB(0xa3947f),  // --k-tool-ink
            .mapBg: RGB(0x100e0c),  // --map-bg
            .srcClaudeCode: RGB(0xd5aa5c),  // --src-claude-code
            .srcCodex: RGB(0x7fb2ae),  // --src-codex
            .srcChatgpt: RGB(0x93b87c),  // --src-chatgpt
            .srcClaudeAi: RGB(0xc395c8),  // --src-claude-ai
            .srcGemini: RGB(0x93a8d8),  // --src-gemini
        ]),
        light: Palette([
            .bg: RGB(0xf6f1e6),  // --bg
            .panel: RGB(0xefe9db),  // --panel
            .panel2: RGB(0xe8e0ce),  // --panel-2
            .panel3: RGB(0xded4bf),  // --panel-3
            .ink: RGB(0x221d16),  // --ink
            .ink2: RGB(0x5d5344),  // --ink-2
            .ink3: RGB(0x736653),  // --ink-3
            .rule: RGB(0xe3dbc9),  // --rule
            .rule2: RGB(0xcabda3),  // --rule-2
            .sel: RGB(0x2c4a7a),  // --sel
            .selBg: RGB(0xdbe3ef),  // --sel-bg
            .selInk: RGB(0xffffff),  // --sel-ink
            .hit: RGB(0x8a5c06),  // --hit
            .hitBg: RGB(0xf6e2b0),  // --hit-bg
            .err: RGB(0x9c2f26),  // --err
            .ok: RGB(0x4a6b32),  // --ok
            .kUser: RGB(0x27486a),  // --k-user
            .kAgent: RGB(0x201c16),  // --k-agent
            .kReason: RGB(0x9550ab),  // --k-reason
            .kTool: RGB(0xa49687),  // --k-tool
            .actLook: RGB(0xb5ada4),  // --act-look
            .actRun: RGB(0xa49687),  // --act-run
            .actChange: RGB(0x688753),  // --act-change
            .kToolInk: RGB(0x6b5f4d),  // --k-tool-ink
            .mapBg: RGB(0xe8e1d1),  // --map-bg
            .srcClaudeCode: RGB(0x7a5c10),  // --src-claude-code
            .srcCodex: RGB(0x17635f),  // --src-codex
            .srcChatgpt: RGB(0x40703a),  // --src-chatgpt
            .srcClaudeAi: RGB(0x7d4383),  // --src-claude-ai
            .srcGemini: RGB(0x3a5590),  // --src-gemini
        ]),
        type: TypeScale(
            sizes: [
                .head: 13,  // --fs-head
                .body: 13,  // --fs-body
                .sub: 11.5,  // --fs-sub
                .meta: 10,  // --fs-meta
                .micro: 9,  // --fs-micro
            ],
            faces: [
                .ui: .serif,  // --ui
                .mono: .monospaced,  // --mono
                .serif: .serif,  // --serif
            ]),
        geometry: Geometry([
            .r1: 0,  // --r-1
            .r2: 0,  // --r-2
            .r3: 0,  // --r-3
            .r4: 0,  // --r-4
            .r5: 2,  // --r-5
            .r6: 2,  // --r-6
            .rowPaddingX: 14,  // --row-px
            .rowPaddingTop: 6,  // --row-pt
            .rowPaddingBottom: 7,  // --row-pb
            .rowLead: 3,  // --row-lead
            .rowGap: 10,  // --row-gap
            .ribbonHeight: 18,  // --rib-h
            .ribbonTrack: 9,  // --rib-track
            .ribbonTop: 6,  // --rib-top
        ]))

    public static let blueprint = Theme(
        name: "blueprint",
        dark: Palette([
            .bg: RGB(0x0f1720),  // --bg
            .panel: RGB(0x0b131b),  // --panel
            .panel2: RGB(0x17212c),  // --panel-2
            .panel3: RGB(0x202c39),  // --panel-3
            .ink: RGB(0xdae5f0),  // --ink
            .ink2: RGB(0x93a7bb),  // --ink-2
            .ink3: RGB(0x6e8496),  // --ink-3
            .rule: RGB(0x1e2c3a),  // --rule
            .rule2: RGB(0x31465b),  // --rule-2
            .sel: RGB(0x4fc0f0),  // --sel
            .selBg: RGB(0x0d3348),  // --sel-bg
            .selInk: RGB(0x04161f),  // --sel-ink
            .hit: RGB(0xf0b95f),  // --hit
            .hitBg: RGB(0x453008),  // --hit-bg
            .err: RGB(0xe2796c),  // --err
            .ok: RGB(0x6fc98a),  // --ok
            .kUser: RGB(0x30a9d5),  // --k-user
            .kAgent: RGB(0xcdd4d9),  // --k-agent
            .kReason: RGB(0x875cbf),  // --k-reason
            .kTool: RGB(0x3c4c5b),  // --k-tool
            .actLook: RGB(0x313b44),  // --act-look
            .actRun: RGB(0x3c4c5b),  // --act-run
            .actChange: RGB(0x38695f),  // --act-change
            .kToolInk: RGB(0x8fa6bd),  // --k-tool-ink
            .mapBg: RGB(0x070d14),  // --map-bg
            .srcClaudeCode: RGB(0xd7b45a),  // --src-claude-code
            .srcCodex: RGB(0x58cfd6),  // --src-codex
            .srcChatgpt: RGB(0x6cc7a0),  // --src-chatgpt
            .srcClaudeAi: RGB(0xb48ce0),  // --src-claude-ai
            .srcGemini: RGB(0x7fa8f5),  // --src-gemini
        ]),
        light: Palette([
            .bg: RGB(0xf4f7fa),  // --bg
            .panel: RGB(0xe9eef5),  // --panel
            .panel2: RGB(0xdde6ef),  // --panel-2
            .panel3: RGB(0xccd9e6),  // --panel-3
            .ink: RGB(0x0d1a26),  // --ink
            .ink2: RGB(0x47607a),  // --ink-2
            .ink3: RGB(0x586d7f),  // --ink-3
            .rule: RGB(0xcfdbe7),  // --rule
            .rule2: RGB(0xa8bdd0),  // --rule-2
            .sel: RGB(0x0a5f8a),  // --sel
            .selBg: RGB(0xd3e6f2),  // --sel-bg
            .selInk: RGB(0xffffff),  // --sel-ink
            .hit: RGB(0x8f5a05),  // --hit
            .hitBg: RGB(0xffe4ae),  // --hit-bg
            .err: RGB(0xa3322a),  // --err
            .ok: RGB(0x2f7a3e),  // --ok
            .kUser: RGB(0x125067),  // --k-user
            .kAgent: RGB(0x1d2227),  // --k-agent
            .kReason: RGB(0x875ac2),  // --k-reason
            .kTool: RGB(0x8ba0b5),  // --k-tool
            .actLook: RGB(0xa8b5c3),  // --act-look
            .actRun: RGB(0x8ba0b5),  // --act-run
            .actChange: RGB(0x478f81),  // --act-change
            .kToolInk: RGB(0x4f6a84),  // --k-tool-ink
            .mapBg: RGB(0xe2e9f1),  // --map-bg
            .srcClaudeCode: RGB(0x6f5300),  // --src-claude-code
            .srcCodex: RGB(0x10646d),  // --src-codex
            .srcChatgpt: RGB(0x216b45),  // --src-chatgpt
            .srcClaudeAi: RGB(0x6c3d9c),  // --src-claude-ai
            .srcGemini: RGB(0x274d9e),  // --src-gemini
        ]),
        type: TypeScale(
            sizes: [
                .head: 12.5,  // --fs-head
                .body: 12,  // --fs-body
                .sub: 11,  // --fs-sub
                .meta: 9.5,  // --fs-meta
                .micro: 8.5,  // --fs-micro
            ],
            faces: [
                .ui: .monospaced,  // --ui
                .mono: .monospaced,  // --mono
                .serif: .serif,  // --serif
            ]),
        geometry: Geometry([
            .r1: 0,  // --r-1
            .r2: 0,  // --r-2
            .r3: 0,  // --r-3
            .r4: 0,  // --r-4
            .r5: 0,  // --r-5
            .r6: 0,  // --r-6
            .rowPaddingX: 12,  // --row-px
            .rowPaddingTop: 6,  // --row-pt
            .rowPaddingBottom: 6,  // --row-pb
            .rowLead: 2,  // --row-lead
            .rowGap: 8,  // --row-gap
            .ribbonHeight: 18,  // --rib-h
            .ribbonTrack: 10,  // --rib-track
            .ribbonTop: 5,  // --rib-top
        ]))

    public static let ink = Theme(
        name: "ink",
        dark: Palette([
            .bg: RGB(0x1a1a1a),  // --bg
            .panel: RGB(0x141414),  // --panel
            .panel2: RGB(0x242424),  // --panel-2
            .panel3: RGB(0x2e2e2e),  // --panel-3
            .ink: RGB(0xe9e9e9),  // --ink
            .ink2: RGB(0xa6a6a6),  // --ink-2
            .ink3: RGB(0x848484),  // --ink-3
            .rule: RGB(0x1f1f1f),  // --rule
            .rule2: RGB(0x2f2f2f),  // --rule-2
            .sel: RGB(0x7ea6d8),  // --sel
            .selBg: RGB(0x1b2836),  // --sel-bg
            .selInk: RGB(0x08131f),  // --sel-ink
            .hit: RGB(0xefb85e),  // --hit
            .hitBg: RGB(0x43310f),  // --hit-bg
            .err: RGB(0xe0796c),  // --err
            .ok: RGB(0x74c98d),  // --ok
            .kUser: RGB(0x85a4a7),  // --k-user
            .kAgent: RGB(0xd4d4d4),  // --k-agent
            .kReason: RGB(0x806b8a),  // --k-reason
            .kTool: RGB(0x484b4f),  // --k-tool
            .actLook: RGB(0x383b3d),  // --act-look
            .actRun: RGB(0x484b4f),  // --act-run
            .actChange: RGB(0x52655f),  // --act-change
            .kToolInk: RGB(0x9a9a9a),  // --k-tool-ink
            .mapBg: RGB(0x0e0e0e),  // --map-bg
            .srcClaudeCode: RGB(0xc2ae7e),  // --src-claude-code
            .srcCodex: RGB(0x7fb6b4),  // --src-codex
            .srcChatgpt: RGB(0x86b590),  // --src-chatgpt
            .srcClaudeAi: RGB(0xb494bb),  // --src-claude-ai
            .srcGemini: RGB(0x93a5c9),  // --src-gemini
        ]),
        light: Palette([
            .bg: RGB(0xfbfaf9),  // --bg
            .panel: RGB(0xf2f1ef),  // --panel
            .panel2: RGB(0xe9e8e6),  // --panel-2
            .panel3: RGB(0xdedcd9),  // --panel-3
            .ink: RGB(0x1b1b1b),  // --ink
            .ink2: RGB(0x5a5a5a),  // --ink-2
            .ink3: RGB(0x6c6c6c),  // --ink-3
            .rule: RGB(0xf0efed),  // --rule
            .rule2: RGB(0xd9d7d4),  // --rule-2
            .sel: RGB(0x2f5d99),  // --sel
            .selBg: RGB(0xdfe8f4),  // --sel-bg
            .selInk: RGB(0xffffff),  // --sel-ink
            .hit: RGB(0x8a5a04),  // --hit
            .hitBg: RGB(0xffe6b4),  // --hit-bg
            .err: RGB(0xa3322a),  // --err
            .ok: RGB(0x2f7a3e),  // --ok
            .kUser: RGB(0x384e51),  // --k-user
            .kAgent: RGB(0x212121),  // --k-agent
            .kReason: RGB(0x80688d),  // --k-reason
            .kTool: RGB(0x999ea4),  // --k-tool
            .actLook: RGB(0xb0b4b8),  // --act-look
            .actRun: RGB(0x999ea4),  // --act-run
            .actChange: RGB(0x6c8980),  // --act-change
            .kToolInk: RGB(0x6a6a6a),  // --k-tool-ink
            .mapBg: RGB(0xe9e8e6),  // --map-bg
            .srcClaudeCode: RGB(0x7d6510),  // --src-claude-code
            .srcCodex: RGB(0x2a6b68),  // --src-codex
            .srcChatgpt: RGB(0x3d6b47),  // --src-chatgpt
            .srcClaudeAi: RGB(0x6d4b76),  // --src-claude-ai
            .srcGemini: RGB(0x4a5c85),  // --src-gemini
        ]),
        type: TypeScale(
            sizes: [
                .head: 13,  // --fs-head
                .body: 12.5,  // --fs-body
                .sub: 11.5,  // --fs-sub
                .meta: 10,  // --fs-meta
                .micro: 9,  // --fs-micro
            ],
            faces: [
                .ui: .default,  // --ui
                .mono: .monospaced,  // --mono
                .serif: .serif,  // --serif
            ]),
        geometry: Geometry([
            .r1: 4,  // --r-1
            .r2: 6,  // --r-2
            .r3: 8,  // --r-3
            .r4: 10,  // --r-4
            .r5: 12,  // --r-5
            .r6: 14,  // --r-6
            .rowPaddingX: 14,  // --row-px
            .rowPaddingTop: 6,  // --row-pt
            .rowPaddingBottom: 6,  // --row-pb
            .rowLead: 4,  // --row-lead
            .rowGap: 10,  // --row-gap
            .ribbonHeight: 18,  // --rib-h
            .ribbonTrack: 7,  // --rib-track
            .ribbonTop: 7,  // --rib-top
        ]))

    public static let gruvboxDerived = Theme(
        name: "gruvbox-derived",
        dark: Palette([
            .bg: RGB(0x32302f),  // --bg
            .panel: RGB(0x282828),  // --panel
            .panel2: RGB(0x3c3836),  // --panel-2
            .panel3: RGB(0x504945),  // --panel-3
            .ink: RGB(0xebdbb2),  // --ink
            .ink2: RGB(0xbdae93),  // --ink-2
            .ink3: RGB(0xa4978b),  // --ink-3
            .rule: RGB(0x3c3836),  // --rule
            .rule2: RGB(0x504945),  // --rule-2
            .sel: RGB(0x79bfc3),  // --sel
            .selBg: RGB(0x193031),  // --sel-bg
            .selInk: RGB(0x0a191a),  // --sel-ink
            .hit: RGB(0xfabd2f),  // --hit
            .hitBg: RGB(0x413310),  // --hit-bg
            .err: RGB(0xfb4934),  // --err
            .ok: RGB(0xb8bb26),  // --ok
            .kUser: RGB(0x83ba70),  // --k-user
            .kAgent: RGB(0xefe5c8),  // --k-agent
            .kReason: RGB(0xc25d78),  // --k-reason
            .kTool: RGB(0x5c544c),  // --k-tool
            .actLook: RGB(0x49443f),  // --act-look
            .actRun: RGB(0x5c544c),  // --act-run
            .actChange: RGB(0x507642),  // --act-change
            .kToolInk: RGB(0xa89984),  // --k-tool-ink
            .mapBg: RGB(0x1d2021),  // --map-bg
            .srcClaudeCode: RGB(0xfe8019),  // --src-claude-code
            .srcCodex: RGB(0x8ec07c),  // --src-codex
            .srcChatgpt: RGB(0xb8bb26),  // --src-chatgpt
            .srcClaudeAi: RGB(0xd3869b),  // --src-claude-ai
            .srcGemini: RGB(0x83a598),  // --src-gemini
        ]),
        light: Palette([
            .bg: RGB(0xf9f5d7),  // --bg
            .panel: RGB(0xfbf1c7),  // --panel
            .panel2: RGB(0xf2e5bc),  // --panel-2
            .panel3: RGB(0xebdbb2),  // --panel-3
            .ink: RGB(0x282828),  // --ink
            .ink2: RGB(0x504945),  // --ink-2
            .ink3: RGB(0x776a5f),  // --ink-3
            .rule: RGB(0xede2c0),  // --rule
            .rule2: RGB(0xd5c4a1),  // --rule-2
            .sel: RGB(0x076678),  // --sel
            .selBg: RGB(0xcbe6eb),  // --sel-bg
            .selInk: RGB(0xfbf1c7),  // --sel-ink
            .hit: RGB(0xb57614),  // --hit
            .hitBg: RGB(0xf1e1b1),  // --hit-bg
            .err: RGB(0x9d0006),  // --err
            .ok: RGB(0x79740e),  // --ok
            .kUser: RGB(0x295038),  // --k-user
            .kAgent: RGB(0x231e1b),  // --k-agent
            .kReason: RGB(0xae4b8a),  // --k-reason
            .kTool: RGB(0xa6998e),  // --k-tool
            .actLook: RGB(0xb8b0a9),  // --act-look
            .actRun: RGB(0xa6998e),  // --act-run
            .actChange: RGB(0x4d8e66),  // --act-change
            .kToolInk: RGB(0x665c54),  // --k-tool-ink
            .mapBg: RGB(0xf2e5bc),  // --map-bg
            .srcClaudeCode: RGB(0xaf3a03),  // --src-claude-code
            .srcCodex: RGB(0x427b58),  // --src-codex
            .srcChatgpt: RGB(0x79740e),  // --src-chatgpt
            .srcClaudeAi: RGB(0x8f3f71),  // --src-claude-ai
            .srcGemini: RGB(0x076678),  // --src-gemini
        ]),
        type: TypeScale(
            sizes: [
                .head: 13,  // --fs-head
                .body: 12.5,  // --fs-body
                .sub: 11.5,  // --fs-sub
                .meta: 10,  // --fs-meta
                .micro: 9,  // --fs-micro
            ],
            faces: [
                .ui: .default,  // --ui
                .mono: .monospaced,  // --mono
                .serif: .serif,  // --serif
            ]),
        geometry: Geometry([
            .r1: 3,  // --r-1
            .r2: 4,  // --r-2
            .r3: 5,  // --r-3
            .r4: 6,  // --r-4
            .r5: 7,  // --r-5
            .r6: 9,  // --r-6
            .rowPaddingX: 12,  // --row-px
            .rowPaddingTop: 7,  // --row-pt
            .rowPaddingBottom: 8,  // --row-pb
            .rowLead: 3,  // --row-lead
            .rowGap: 9,  // --row-gap
            .ribbonHeight: 18,  // --rib-h
            .ribbonTrack: 9,  // --rib-track
            .ribbonTop: 6,  // --rib-top
        ]))

    public static let solarizedDerived = Theme(
        name: "solarized-derived",
        dark: Palette([
            .bg: RGB(0x002b36),  // --bg
            .panel: RGB(0x073642),  // --panel
            .panel2: RGB(0x0c4655),  // --panel-2
            .panel3: RGB(0x1a5566),  // --panel-3
            .ink: RGB(0xeee8d5),  // --ink
            .ink2: RGB(0xa6b4b5),  // --ink-2
            .ink3: RGB(0x879ea4),  // --ink-3
            .rule: RGB(0x0c3e4b),  // --rule
            .rule2: RGB(0x194a57),  // --rule-2
            .sel: RGB(0x5aace7),  // --sel
            .selBg: RGB(0x0c3245),  // --sel-bg
            .selInk: RGB(0x002b36),  // --sel-ink
            .hit: RGB(0xb58900),  // --hit
            .hitBg: RGB(0x3d2f05),  // --hit-bg
            .err: RGB(0xdc322f),  // --err
            .ok: RGB(0x859900),  // --ok
            .kUser: RGB(0x36baaf),  // --k-user
            .kAgent: RGB(0xdce0e0),  // --k-agent
            .kReason: RGB(0x6d72c5),  // --k-reason
            .kTool: RGB(0x44555a),  // --k-tool
            .actLook: RGB(0x394347),  // --act-look
            .actRun: RGB(0x44555a),  // --act-run
            .actChange: RGB(0x2b736d),  // --act-change
            .kToolInk: RGB(0x8eabb4),  // --k-tool-ink
            .mapBg: RGB(0x001e26),  // --map-bg
            .srcClaudeCode: RGB(0xcb4b16),  // --src-claude-code
            .srcCodex: RGB(0x2aa198),  // --src-codex
            .srcChatgpt: RGB(0x859900),  // --src-chatgpt
            .srcClaudeAi: RGB(0xd33682),  // --src-claude-ai
            .srcGemini: RGB(0x268bd2),  // --src-gemini
        ]),
        light: Palette([
            .bg: RGB(0xfdf6e3),  // --bg
            .panel: RGB(0xeee8d5),  // --panel
            .panel2: RGB(0xe9dfc4),  // --panel-2
            .panel3: RGB(0xddd2b0),  // --panel-3
            .ink: RGB(0x002b36),  // --ink
            .ink2: RGB(0x3b4e54),  // --ink-2
            .ink3: RGB(0x556a71),  // --ink-3
            .rule: RGB(0xece5d0),  // --rule
            .rule2: RGB(0xdfd5b9),  // --rule-2
            .sel: RGB(0x0b578e),  // --sel
            .selBg: RGB(0xcfe0ed),  // --sel-bg
            .selInk: RGB(0xfdf6e3),  // --sel-ink
            .hit: RGB(0xb58900),  // --hit
            .hitBg: RGB(0xf4e2af),  // --hit-bg
            .err: RGB(0xdc322f),  // --err
            .ok: RGB(0x859900),  // --ok
            .kUser: RGB(0x154d49),  // --k-user
            .kAgent: RGB(0x031e25),  // --k-agent
            .kReason: RGB(0x5e62bf),  // --k-reason
            .kTool: RGB(0x849ba2),  // --k-tool
            .actLook: RGB(0xa0b0b4),  // --act-look
            .actRun: RGB(0x849ba2),  // --act-run
            .actChange: RGB(0x2e8b83),  // --act-change
            .kToolInk: RGB(0x49666e),  // --k-tool-ink
            .mapBg: RGB(0xe8e0c8),  // --map-bg
            .srcClaudeCode: RGB(0xcb4b16),  // --src-claude-code
            .srcCodex: RGB(0x2aa198),  // --src-codex
            .srcChatgpt: RGB(0x859900),  // --src-chatgpt
            .srcClaudeAi: RGB(0xd33682),  // --src-claude-ai
            .srcGemini: RGB(0x268bd2),  // --src-gemini
        ]),
        type: TypeScale(
            sizes: [
                .head: 13,  // --fs-head
                .body: 12.5,  // --fs-body
                .sub: 11.5,  // --fs-sub
                .meta: 10,  // --fs-meta
                .micro: 9,  // --fs-micro
            ],
            faces: [
                .ui: .default,  // --ui
                .mono: .monospaced,  // --mono
                .serif: .serif,  // --serif
            ]),
        geometry: Geometry([
            .r1: 3,  // --r-1
            .r2: 4,  // --r-2
            .r3: 5,  // --r-3
            .r4: 6,  // --r-4
            .r5: 7,  // --r-5
            .r6: 9,  // --r-6
            .rowPaddingX: 12,  // --row-px
            .rowPaddingTop: 7,  // --row-pt
            .rowPaddingBottom: 8,  // --row-pb
            .rowLead: 3,  // --row-lead
            .rowGap: 9,  // --row-gap
            .ribbonHeight: 18,  // --rib-h
            .ribbonTrack: 9,  // --rib-track
            .ribbonTop: 6,  // --rib-top
        ]))

    /// Every direction compiled into this build, in the order they were generated.
    ///
    /// Generated rather than written, so this list cannot disagree with what is above it:
    /// a direction that is compiled in is one the app offers and one `--verify-theme`
    /// measures. That equivalence is what makes "everything the picker offers is fenced"
    /// enforceable rather than a habit (docs/DECISIONS.md ADR 25).
    public static let directions: [Theme] = [terminal, paper, blueprint, ink, gruvboxDerived, solarizedDerived]

    /// What the app draws when nobody has chosen: the first direction named on the command
    /// line that generated this file.
    ///
    /// The environment's default, so no view names a direction and no view names a value.
    /// Changing which direction that is stays a regeneration of this one file — the claim
    /// the seam makes, and `git diff --stat` is the evidence.
    public static let shipped = terminal
}
