[package]
name = "cs-import"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cs-archive = { path = "../cs-archive" }
cs-core = { path = "../cs-core" }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
